### ISSUE TITLE
implementation questions

### ISSUE THREAD

**Issue by shaodan-personal** [huangzehao/Super-Resolution.Benckmark#3]
@huangzehao Do you have plan to implement the FSRCNN method? We are now working on SR, We find you bring very useful information and research results. Would you mind contact me (shaodan at hisilicon dot com) for future corporation? Thank you.

**Comment by huangzehao** [comment]
Hi, thanks for your attention! There is an official FSRCNN implement in caffe. Check http://mmlab.ie.cuhk.edu.hk/projects/FSRCNN.html and you will find it.
