### ISSUE TITLE
What implementation of bicubic interpolation is used?

### ISSUE THREAD

**Issue by Valdas3** [huangzehao/Super-Resolution.Benckmark#4]
Hi @huangzehao, thank you for creating this great resource. It was a great help for writing my master's thesis so far.
Bicubic interpolation gets included in every paper as a minimum baseline which must be surpassed. But I have not found any mention about which specific implementation is used. Searching online I found a couple of different algorithms/implementations which are called "bicubic". Is there some standard implementation which is used by everyone? I realize that bicubic interpolation is by far the least interesting thing here but it would be nice to have a source of concrete implementation for completeness   :smile:

**Comment by huangzehao** [comment]
Hi, most of codes use matlab imresize function with bicubic method.

**Comment by Valdas3** [comment]
Thank you
